#!/bin/zsh

packages=("${(@f)$(jq -r '.["bs-dependencies"][]' < bsconfig.json)}")

for package ($packages) ; do
  echo "Copying $package..."
  src="./node_modules/$package/lib/js/src/"
  dest="./lib/node_modules/$package/lib/js/src/"
  mkdir -p $dest
  rsync -a $src $dest
done

